### ISSUE TITLE
Redhat SSO 7.6 GA ( keycloak 18.0.0)

### ISSUE THREAD

**Issue by nhatpv1307** [mixxplorer/keycloak-mfa-enforcer#1]
private boolean userHasMFA(UserModel user) {
        // Check whether we need to trigger this step in the authentication flow.
        // This is the case, the user neither has MFA activated and didn't select a type of MFA, yet.

        final boolean hasOTP = user.credentialManager().isConfiguredFor(OTPCredentialModel.TYPE);

        final boolean hasWebAuthn = user.credentialManager().isConfiguredFor(WebAuthnCredentialModel.TYPE_TWOFACTOR);
        final boolean hasMFA = hasOTP || hasWebAuthn;

        return hasMFA;
    }
    
    i use Redhat SSO 7.6 GA ( keycloak 18.0.0), 
    How should the above code be handled? Can you help me?

**Comment by nhatpv1307** [comment]
private boolean userHasMFA(AuthenticationFlowContext context) {
        RealmModel realm = context.getRealm();
        UserModel user = context.getUser();
        KeycloakSession session = context.getSession();

        boolean hasOTP = session.userCredentialManager()
                .isConfiguredFor(realm, user, OTPCredentialModel.TYPE);
        log.info("Otp is configured: " + hasOTP);
       
Thank you, this is how I use it with version 18

**Comment by felix-gohla** [comment]
Hi @nhatpv1307,

sorry for the late reply.
As RedHat SSO 7.6 is basically EOL ([full support](https://access.redhat.com/support/policy/updates/jboss_notes#p_sso) ended on 30 June 2022), we won't incorporate those changes anymore.

However, thank you for sharing your solution for Keycloak 18 / SSO 7.6! 😊
